package com.ecommerce.one.ecommerce.mapper;

import com.ecommerce.one.ecommerce.domain.orderd;
import com.ecommerce.one.ecommerce.domain.orderdExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface orderdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderd
     *
     * @mbg.generated Thu May 21 23:22:38 CST 2020
     */
    long countByExample(orderdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderd
     *
     * @mbg.generated Thu May 21 23:22:38 CST 2020
     */
    int deleteByExample(orderdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderd
     *
     * @mbg.generated Thu May 21 23:22:38 CST 2020
     */
    int deleteByPrimaryKey(Integer orderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderd
     *
     * @mbg.generated Thu May 21 23:22:38 CST 2020
     */
    int insert(orderd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderd
     *
     * @mbg.generated Thu May 21 23:22:38 CST 2020
     */
    int insertSelective(orderd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderd
     *
     * @mbg.generated Thu May 21 23:22:38 CST 2020
     */
    List<orderd> selectByExample(orderdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderd
     *
     * @mbg.generated Thu May 21 23:22:38 CST 2020
     */
    orderd selectByPrimaryKey(Integer orderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderd
     *
     * @mbg.generated Thu May 21 23:22:38 CST 2020
     */
    int updateByExampleSelective(@Param("record") orderd record, @Param("example") orderdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderd
     *
     * @mbg.generated Thu May 21 23:22:38 CST 2020
     */
    int updateByExample(@Param("record") orderd record, @Param("example") orderdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderd
     *
     * @mbg.generated Thu May 21 23:22:38 CST 2020
     */
    int updateByPrimaryKeySelective(orderd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderd
     *
     * @mbg.generated Thu May 21 23:22:38 CST 2020
     */
    int updateByPrimaryKey(orderd record);
}