package com.ecommerce.one.ecommerce.mapper;

import com.ecommerce.one.ecommerce.domain.wishlist;
import com.ecommerce.one.ecommerce.domain.wishlistExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface wishlistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wishlist
     *
     * @mbg.generated Sat May 23 21:26:19 CST 2020
     */
    long countByExample(wishlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wishlist
     *
     * @mbg.generated Sat May 23 21:26:19 CST 2020
     */
    int deleteByExample(wishlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wishlist
     *
     * @mbg.generated Sat May 23 21:26:19 CST 2020
     */
    int insert(wishlist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wishlist
     *
     * @mbg.generated Sat May 23 21:26:19 CST 2020
     */
    int insertSelective(wishlist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wishlist
     *
     * @mbg.generated Sat May 23 21:26:19 CST 2020
     */
    List<wishlist> selectByExample(wishlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wishlist
     *
     * @mbg.generated Sat May 23 21:26:19 CST 2020
     */
    int updateByExampleSelective(@Param("record") wishlist record, @Param("example") wishlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wishlist
     *
     * @mbg.generated Sat May 23 21:26:19 CST 2020
     */
    int updateByExample(@Param("record") wishlist record, @Param("example") wishlistExample example);
}