package com.ecommerce.one.ecommerce.domain;

import java.math.BigDecimal;
import java.util.Date;

public class payment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.payment_id
     *
     * @mbg.generated Thu May 21 23:23:09 CST 2020
     */
    private Short paymentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.customer_id
     *
     * @mbg.generated Thu May 21 23:23:09 CST 2020
     */
    private Short customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.staff_id
     *
     * @mbg.generated Thu May 21 23:23:09 CST 2020
     */
    private Byte staffId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.rental_id
     *
     * @mbg.generated Thu May 21 23:23:09 CST 2020
     */
    private Integer rentalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.amount
     *
     * @mbg.generated Thu May 21 23:23:09 CST 2020
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.payment_date
     *
     * @mbg.generated Thu May 21 23:23:09 CST 2020
     */
    private Date paymentDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.last_update
     *
     * @mbg.generated Thu May 21 23:23:09 CST 2020
     */
    private Date lastUpdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.payment_id
     *
     * @return the value of payment.payment_id
     *
     * @mbg.generated Thu May 21 23:23:09 CST 2020
     */
    public Short getPaymentId() {
        return paymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.payment_id
     *
     * @param paymentId the value for payment.payment_id
     *
     * @mbg.generated Thu May 21 23:23:09 CST 2020
     */
    public void setPaymentId(Short paymentId) {
        this.paymentId = paymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.customer_id
     *
     * @return the value of payment.customer_id
     *
     * @mbg.generated Thu May 21 23:23:09 CST 2020
     */
    public Short getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.customer_id
     *
     * @param customerId the value for payment.customer_id
     *
     * @mbg.generated Thu May 21 23:23:09 CST 2020
     */
    public void setCustomerId(Short customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.staff_id
     *
     * @return the value of payment.staff_id
     *
     * @mbg.generated Thu May 21 23:23:09 CST 2020
     */
    public Byte getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.staff_id
     *
     * @param staffId the value for payment.staff_id
     *
     * @mbg.generated Thu May 21 23:23:09 CST 2020
     */
    public void setStaffId(Byte staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.rental_id
     *
     * @return the value of payment.rental_id
     *
     * @mbg.generated Thu May 21 23:23:09 CST 2020
     */
    public Integer getRentalId() {
        return rentalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.rental_id
     *
     * @param rentalId the value for payment.rental_id
     *
     * @mbg.generated Thu May 21 23:23:09 CST 2020
     */
    public void setRentalId(Integer rentalId) {
        this.rentalId = rentalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.amount
     *
     * @return the value of payment.amount
     *
     * @mbg.generated Thu May 21 23:23:09 CST 2020
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.amount
     *
     * @param amount the value for payment.amount
     *
     * @mbg.generated Thu May 21 23:23:09 CST 2020
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.payment_date
     *
     * @return the value of payment.payment_date
     *
     * @mbg.generated Thu May 21 23:23:09 CST 2020
     */
    public Date getPaymentDate() {
        return paymentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.payment_date
     *
     * @param paymentDate the value for payment.payment_date
     *
     * @mbg.generated Thu May 21 23:23:09 CST 2020
     */
    public void setPaymentDate(Date paymentDate) {
        this.paymentDate = paymentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.last_update
     *
     * @return the value of payment.last_update
     *
     * @mbg.generated Thu May 21 23:23:09 CST 2020
     */
    public Date getLastUpdate() {
        return lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.last_update
     *
     * @param lastUpdate the value for payment.last_update
     *
     * @mbg.generated Thu May 21 23:23:09 CST 2020
     */
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment
     *
     * @mbg.generated Thu May 21 23:23:09 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        payment other = (payment) that;
        return (this.getPaymentId() == null ? other.getPaymentId() == null : this.getPaymentId().equals(other.getPaymentId()))
            && (this.getCustomerId() == null ? other.getCustomerId() == null : this.getCustomerId().equals(other.getCustomerId()))
            && (this.getStaffId() == null ? other.getStaffId() == null : this.getStaffId().equals(other.getStaffId()))
            && (this.getRentalId() == null ? other.getRentalId() == null : this.getRentalId().equals(other.getRentalId()))
            && (this.getAmount() == null ? other.getAmount() == null : this.getAmount().equals(other.getAmount()))
            && (this.getPaymentDate() == null ? other.getPaymentDate() == null : this.getPaymentDate().equals(other.getPaymentDate()))
            && (this.getLastUpdate() == null ? other.getLastUpdate() == null : this.getLastUpdate().equals(other.getLastUpdate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment
     *
     * @mbg.generated Thu May 21 23:23:09 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPaymentId() == null) ? 0 : getPaymentId().hashCode());
        result = prime * result + ((getCustomerId() == null) ? 0 : getCustomerId().hashCode());
        result = prime * result + ((getStaffId() == null) ? 0 : getStaffId().hashCode());
        result = prime * result + ((getRentalId() == null) ? 0 : getRentalId().hashCode());
        result = prime * result + ((getAmount() == null) ? 0 : getAmount().hashCode());
        result = prime * result + ((getPaymentDate() == null) ? 0 : getPaymentDate().hashCode());
        result = prime * result + ((getLastUpdate() == null) ? 0 : getLastUpdate().hashCode());
        return result;
    }
}